### ISSUE TITLE
Application.Current null

### ISSUE THREAD

**Issue by albusorin** [jonathanpeppers/Xamarin.Forms.Mocks#11]
Nice package!!!
But, sometimes is needed the Application.Current to set some resources and so on, but this is nulll

Thanks,
Sorin

**Comment by albusorin** [comment]
One solution can be:
```

[SetUp]
public void SetUp()
{
     Xamarin.Forms.Mocks.MockForms.Init();
     new ApplicationMock();
}

    public class ApplicationMock : Application
    {
        public ApplicationMock()
        {
        }

        public ApplicationMock(Page startPage) : this()
        {
            Current.MainPage = startPage;
        }

        public bool Initialized { get; private set; }

        protected void OnInitialized()
        {
            Initialized = true;
        }
    }
```

**Comment by jonathanpeppers** [comment]
Hi @albusorin ,

So we are not doing anything with `Application.Current`, because a "mock" application doesn't help much.

You can do something like this in your own tests:
```csharp
Application.Current = new YourApplicationClass();
```

`MockForms.Init()` should probably not set `Application.Current` because you really want your own `Application` class with your `Resources` if that is what you are trying to test.

Does that make sense, or did I miss something? Let me know if there is something `internal` that prevents this from working.
