### ISSUE TITLE
Correct way to mock Device.BeginInvokeOnMainThread

### ISSUE THREAD

**Issue by 15mgm15** [jonathanpeppers/Xamarin.Forms.Mocks#17]
Hello Jon, I am having a specific scenario where my unit test never ends it stays like in a weird limbo state, I am trying to test this method:

```
//Command:
public override Command SendMessageCommand { get; set; }

public NewMessageViewModel(Office office) : this(new DependencyServiceWrapper(), office) { }

public NewMessageViewModel(IDependencyService dependencyService, Office office) : base(dependencyService)
{
    Office = office;
    Init();
}

//Called in the constructor.
void Init()
{
    SendMessageCommand = new Command(async () => await SendMessage());
    OnPropertyChanged(nameof(OfficeName));
}

protected override async Task SendMessage()
{
    try
    {
        SuccessfulRequest = false;

        if (string.IsNullOrEmpty(SubjectText))
        {
            await PageReference.DisplayAlert(Strings.MessageSubjectErrorTitle, Strings.MessageSubjectErrorDetail, Strings.Ok);
        }
        
        if (string.IsNullOrEmpty(MessageBodyText))
        {
            await PageReference.DisplayAlert(Strings.MessageErrorTitle, Strings.MessageErrorDetail, Strings.Ok);
        }

        if (IsBusy == true || Office == null)
        {
            return;
        }

        if(!Office.Id.HasValue)
        {
            return;
        }

        IsBusy = true;

        var subject = string.IsNullOrEmpty(SubjectText) ? string.Empty : SubjectText;

        var message = new CreateMessagesRequest(Office.Id.Value, subject, MessageBodyText);
        var response = await MessageService.CreateMessages(message, new CancellationToken()).ConfigureAwait(false);

        if(response.Success)
        {
            SuccessfulRequest = true;

            //Issue
            DeviceWrapper.BeginInvokeOnMainThread(async () =>
            {
                ApplicationMessenger.Send(new ShowNewMessageBanner(), response.Success);
                await Navigation.PopAsync();
            });
        }

    }
    catch (Exception ex)
    {
        System.Diagnostics.Debug.WriteLine("Class: {0} Method: {1} Exception: {2}", nameof(ReplyMessageViewModel), nameof(SendMessage), ex.Message);
    }
    finally
    {
        IsBusy = false;
    }
}
```
I am pretty sure that the problem is the `DeviceWrapper.BeginInvokeOnMainThread` because if I get rid of it my test passes normally. This is my unit test:

```
[Test]
public void SendMessageIsSuccessful()
{
    var myTeamViewModel = new NewMessageViewModel(DependencyService, new Office
    {
        Id = AutoFixture.Create<int>(),
        Name = AutoFixture.Create<string>()
    })
    {
        SubjectText = AutoFixture.Create<string>(),
        MessageBodyText = AutoFixture.Create<string>()
    };

    Assert.NotNull(myTeamViewModel.Office.Id.Value);
    Assert.NotNull(myTeamViewModel.SubjectText);
    Assert.NotNull(myTeamViewModel.MessageBodyText);

    var response = new CreateMessagesResponse { Success = true };

    MessagesServiceMock.Setup(Mock => Mock.CreateMessages(It.IsAny<CreateMessagesRequest>(), It.IsAny<CancellationToken>())).ReturnsAsync(response);
    ApplicationMessengerMock.Setup(Mock => Mock.Send(It.IsAny<ShowNewMessageBanner>(), true));

    myTeamViewModel.SendMessageCommand.Execute(null);

    MessagesServiceMock.Verify(mock => mock.CreateMessages(It.IsAny<CreateMessagesRequest>(), It.IsAny<CancellationToken>()), Times.Once());

    Assert.IsTrue(myTeamViewModel.SuccessfulRequest);
    Assert.IsFalse(myTeamViewModel.IsBusy);
}
```
There may be some thread or race conditions involved because my unit test never returns something either failed or success or inconclusive. I am wondering what would be the correct way to mock or test this.

**Comment by jonathanpeppers** [comment]
The problem I see with your test is that `ICommand.Execute` returns `void`.

How will the test know the task finished? In a past project, I had written my own `async` version of `ICommand`, but maybe it would be easier to have the test call `SendMessage` directly so it can `await` it?

The other option you could try is using Xamarin.Forms.Mocks from source, and change this [line](https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/master/Xamarin.Forms.Mocks/MockForms.cs#L70) to use `Task.Factory.StartNew` instead of just running the action.

**Comment by 15mgm15** [comment]
Thanks for the suggestion Jonathan!

**Comment by 15mgm15** [comment]
Hello Jonathan!

Do you know a wat to mock a SQLiteConnection? `new SQLiteConnection(localFilePath);` I've tried `":memory:"` without any success. Or I am just going to in the wrong direction?

**Comment by jonathanpeppers** [comment]
I generally would mock the database at a higher layer than what it sounds like you are trying.

So if you have an interface to represent your database (or could be a base/abstract class):
```
interface IDatabase {
    Task<List<Order>> GetOrders();
}
```

The "mock" one could basically do whatever you want:
```
class MockDatabase : IDatabase {
    public Task<List<Order>> GetOrders() {
        //Just return a new List<T>
    }
}
```

The "real" one would use `SQLiteConnection` or whatever the real code needs to do.  Your ViewModels should only reference `IDatabase` so you can swap it out with a mock one.

I would use this method for any unit tests with ViewModels--you can even create mock databases in the tests or use a library like `Moq` if needed.

If you *are* explicitly trying to test your SQLite database code, your unit tests can use SQLite on Mac or Windows. Just put the database in a temp file in the tests instead of wherever it puts the database in your app.

I'm going to close this, as it seems off-topic from Xamarin.Forms.Mocks. But feel free to open a new issue if you find a problem with Xamarin.Forms.Mocks.
