### ISSUE TITLE
Init() throws TypeLoadException in new Xamarin.Forms

### ISSUE THREAD

**Issue by DavidOndrus** [jonathanpeppers/Xamarin.Forms.Mocks#2]
Hi, I updated to the new version of Xamarin.Forms package and (probably) due to the Device class redesign, Init() now throws an exception in my SetUp() method in Unit tests. I've checked and in Init() method, PlatformServices are called but I can't figure out how to solve it by myself.

DETAILS:
`"Method 'get_RuntimePlatform' in type 'PlatformServices' from assembly 'Xamarin.Forms.Core.UnitTests, Version=1.0.6226.39941, Culture=neutral, PublicKeyToken=null' does not have an implementation.":"PlatformServices"`

**Comment by jonathanpeppers** [comment]
Hi David,

Yes, Xamarin.Forms has changed an interface in 2.3.4.

I think I'll take a look tonight, but I think I could push a new version of Xamarin.Forms.Mocks that requires Xamarin.Forms 2.3.4+. If you need older than 2.3.4, you can use the existing NuGet package of Xamarin.Forms.Mocks.

It might actually make sense if I made the version of Xamarin.Forms.Mocks parallel with the version  number of Xamarin.Forms. I'll probably do this as well.

**Comment by jonathanpeppers** [comment]
@DavidOndrus let me know if 2.3.4.1 on NuGet fixes your issue.

**Comment by DavidOndrus** [comment]
It works but I needed to downgrade Xamarin.Forms to the latest stable version (2.3.4.231) because it doesn't work on the latest prerelease (2.3.5.233-pre1).
Thank you for your time and this update.

**Comment by jonathanpeppers** [comment]
I'll see what it takes to support 2.3.5 at some point, it is still a beta.

Sent from my phone



On Sat, Apr 15, 2017 at 2:35 AM -0500, "DavidOndrus" <notifications@github.com<mailto:notifications@github.com>> wrote:


It works but I needed to downgrade Xamarin.Forms to the latest stable version (2.3.4.231) because it doesn't work on the latest prerelease (2.3.5.233-pre1).
Thank you for your time and this update.
