### ISSUE TITLE
Inconsistent Results for OpenUri Tests

### ISSUE THREAD

**Issue by MooVC** [jonathanpeppers/Xamarin.Forms.Mocks#42]
I have three XUnit tests, each residing within their own test class, that all use the OpenUriAction delegate to capture the Uri passed to Device.OpenUri.  When tested individually, each test passes without issue.  When tested together, only one of the three tests pass.  Each test class calls Init within the constructor, the expectation being that each would be run in isolation.  Can you please indicate if this is a bug or if the manner to which it is being used is incorrect?

The issue has been encountered with: v3.5.0.1.

**Comment by jonathanpeppers** [comment]
Are these tests running in parallel?

The types in Xamarin.Forms are static -- so they are definitely going to collide if more than one is running.

**Comment by MooVC** [comment]
Hi @jonathanpeppers,

Thank you for coming back on this so quickly.

As I understand it, XUnit generates an instance of each class and the tests contained within that instance are executed sequentially, but tests from another instances may be executed in parallel.  In this case, the tests reside in different classes and thus, I would expect them to run in parallel.  As an experiment, I merged the three classes together and ran it and it worked fine every time.  Sadly, merging them in this fashion would break the testing convention, but it does serve to validate the theory.  I'm guessing the only way to obtain the desired behavior would be to have each test run in a different AppDomain, but that does seem like overkill :)

**Comment by jonathanpeppers** [comment]
Yeah all this stuff is `static`: https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/31ed5a7b81c7cdef5f217ac84cb864342e2a1647/Xamarin.Forms.Mocks/MockForms.cs#L19-L24

Since Xamarin.Forms' implementation uses `static` classes, I don't know what we can do here 😞. I could see there being other strange problems running tests in parallel.

I have not used this library with XUnit myself. If you have any inclination to add to our docs for Xamarin.Forms.Mocks & XUnit. Send a PR, it would be awesome, thanks!

**Comment by MooVC** [comment]
Thanks @jonathanpeppers - Appreciate the help.
