### ISSUE TITLE
Unable to use Entry.IsFocused in tests

### ISSUE THREAD

**Issue by mjfreelancing** [jonathanpeppers/Xamarin.Forms.Mocks#54]
The IsFocused property of Entry appears to be set via its renderer. I've been unable to work out how we can mock the Entry control so IsFocused returns true after calling Focus().

```csharp
[Fact]
public void TestMethod()
{
  var entry = new Entry();
  entry.Focus();

  entry.IsFocused.Should().BeTrue();

  // the remainder of my test will go here - but the above assertion fails
}
```

I'm hoping you've got some ideas on how this might be achieved.

**Comment by jonathanpeppers** [comment]
I think you would have to subscribe to `FocusChangeRequested`:

https://github.com/xamarin/Xamarin.Forms/blob/5a8858277ad381d055cdcb0fa6634bfc684c30b1/Xamarin.Forms.Core/VisualElement.cs#L626-L637

Then do:
```csharp
entry.SetValue (Entry.FocusedProperty, true);
```

I don't know how Xamarin.Forms.Mocks would do it in an automated way, but you could set that up in your test.

In the end, it could make the test above pointless, because you're just testing Xamarin.Forms plumbing and not your code. It might make sense if your tests are doing other things, though?

**Comment by mjfreelancing** [comment]
Thanks, I'll take a look. Yes, my actual test is for a behavior that relies on the Entry having focus. My snippet was only for example purposes.

**Comment by mjfreelancing** [comment]
The call to SetValue() is so obvious now, I hadn't even considered that. I can simply call this instead of Focus() for my behavior testing needs. Thanks again.

**Comment by mjfreelancing** [comment]
I spoke too soon. The property is defined readonly.

**Comment by mjfreelancing** [comment]
I solved the problem using this in place of calling Focus() on the Entry control

```csharp
var setValueMethod = typeof(BindableObject)
  .GetMethod("SetValue",
    BindingFlags.Instance | BindingFlags.NonPublic,
    null,
    new Type[] {typeof(BindableProperty), typeof(object), typeof(bool), typeof(bool)},
    null
  );

setValueMethod.Invoke(entry, new object[] {Entry.IsFocusedProperty, true, false, false});
```

Your idea of using SetValue() put me on the right path.
