### ISSUE TITLE
Bump to XF 5.0

### ISSUE THREAD

**Issue by adamhill** [jonathanpeppers/Xamarin.Forms.Mocks#75]
Any chance of  this happening before Maui release?

**Comment by jonathanpeppers** [comment]
Are you hitting an issue using Xamarin.Forms 5? I normally don’t update this package if it continues to work.

**Comment by mjeson** [comment]
Hello, thank you for this wonderful mocking package !

Yes, I am hitting an issue using Xamarin.Forms 5, (exact version 5.0.0.2515). It happens on instantiating a page, on InitializingComponent();

Error message below:

{"Method not found: 'Boolean Xamarin.Forms.Internals.ResourceLoader.get_IsEnabled()'."}

**Comment by jonathanpeppers** [comment]
@mjeson can you find the exact version that breaks? When this issue was filed, it was working with some version of Xamarin.Forms 5.

The error above seems like you need to update to latest Xamarin.Forms, it looks like this `ResourceLoader.IsEnabled` property was added ~2 years ago:

https://github.com/xamarin/Xamarin.Forms/blob/c1a88782ee39d1218c51058cc913e371653cfd04/Xamarin.Forms.Core/Internals/ResourceLoader.cs#L39-L41

**Comment by mjeson** [comment]
Hi @jonathanpeppers . Thank you for replying. Turns out this is my issue. I had a mismatch on the Xamarin Forms version. The mobile project is running on Xamarin Forms 5.0.0.2515, but the test project running on Xamarin Forms 4.7. Updating the test project to Xamarin Forms 5 solves my issue. Thank you so much!
